### Spring properties
### Service registers under this name
spring:
  application:
    name: app-main-service
 
# HTTP Server (Tomcat) Port   
server:
  port: 8083
  
# Discovery Server Access
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
#      defaultZone: ${EUREKA_URI:http://localhost:8081/eureka}
  instance:
    hostname: localhost