# Eureka Client Configuration
server:
  port: 8086
spring:
  application:
    name: training-service
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
  instance:
    hostname: localhost
#Note: if you use this prop, zuul cannot forward request to target server /url   
    #preferIpAddress: true