server:
  port: 8082
    
spring:
  application:
    name: zuul-service

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8081/eureka
  instance:
    hostname: localhost
    #hostname: ${THE_HOST}
    
#Ribbon (Feign), disable for now
ribbon:
  eureka:
    enabled: true
   
#Zuul Configs
zuul:
#  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    app-main-service:
      path: /mods-api/**
      serviceId: APP-MAIN-SERVICE
    test-service:
      path: /test-api/**
      serviceId: TEST-SERVICE
      #      url: http://localhost:8084


    