server:
  port: 8083
    
spring:
  application:
    name: user-service

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8081/eureka
  instance:
    hostname: localhost
    #hostname: ${THE_HOST}