### Spring properties
### Service registers under this name
spring:
  application:
    name: payment-service
 
# HTTP Server (Tomcat) Port
server:
  port: 8087
  
# Discovery Server Access
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
#      defaultZone: ${EUREKA_URI:http://localhost:8081/eureka}
  instance:
    hostname: localhost